services:

  sus-manager-db:
    container_name: postgres-sus-manager
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sus_manager_database
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - TZ=America/Sao_Paulo
    ports:
      - "5433:5432"
    networks:
      - sus-manager-network

  sus-manager-app:
    container_name: java-sus-manager
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "mvn clean install && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar target/SusManager.jar"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8081:8080"
      - "5006:5005"
    networks:
      - sus-manager-network
      - rabbitmq_go_net
    depends_on:
      - sus-manager-db

networks:
  rabbitmq_go_net:
    external: true
  sus-manager-network:
    name: sus-manager-network