networks:
  sus-integrated-network:
    name: sus-integrated-network
  sus-manager-network:
    name: sus-manager-network
  sus-unity-network:
    name: sus-unity-network
  rabbitmq_go_net:
    name: rabbitmq_go_net

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  sus-integrated-db:
    container_name: postgres-sus-integrated
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./sus_integrated/data/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sus_integrated_database
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    networks:
      - sus-integrated-network

  sus-integrated-app:
    container_name: java-sus-integrated
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./sus_integrated:/app
    working_dir: /app
    command: bash -c "mvn clean install && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar target/sus_integrated.jar"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - sus-integrated-network
      - rabbitmq_go_net
    depends_on:
      - sus-integrated-db

  sus-manager-db:
    container_name: postgres-sus-manager
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./sus_manager/data/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sus_manager_database
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - TZ=America/Sao_Paulo
    ports:
      - "5433:5432"
    networks:
      - sus-manager-network

  sus-manager-app:
    container_name: java-sus-manager
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./sus_manager:/app
    working_dir: /app
    command: bash -c "mvn clean install && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar target/SusManager.jar"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8081:8080"
      - "5006:5005"
    networks:
      - sus-manager-network
      - rabbitmq_go_net
    depends_on:
      - sus-manager-db

  sus-unity-db:
    container_name: postgres-sus-unity
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./sus_unity/data/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sus_unity_database
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - TZ=America/Sao_Paulo
    ports:
      - "5434:5432"
    networks:
      - sus-unity-network

  sus-unity-app:
    container_name: java-sus-unity
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./sus_unity:/app
    working_dir: /app
    command: bash -c "mvn clean install && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar target/SusUnity.jar"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8082:8080"
      - "5007:5005"
    networks:
      - sus-unity-network
      - rabbitmq_go_net
    depends_on:
      - sus-unity-db
