services:

  integrated-sus-db:
    container_name: postgres-integrated-sus
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=integrated_sus_database
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    networks:
      - integrated-sus-network

  integrated-sus-app:
    container_name: java-integrated-sus
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "mvn clean install && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar target/IntegratedSus.jar"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - integrated-sus-network
      - rabbitmq_go_net
    depends_on:
      - integrated-sus-db

networks:
  rabbitmq_go_net:
    external: true
  integrated-sus-network:
    name: integrated-sus-network