services:

  sus-integrated-db:
    container_name: postgres-sus-integrated
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sus_integrated_database
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    networks:
      - sus-integrated-network

  sus-integrated-app:
    container_name: java-sus-integrated
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "mvn clean install && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar target/sus_integrated.jar"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - sus-integrated-network
      - rabbitmq_go_net
    depends_on:
      - sus-integrated-db

networks:
  rabbitmq_go_net:
    external: true
  sus-integrated-network:
    name: sus-integrated-network