services:

  sus-scheduling-db:
    container_name: postgres-sus-scheduling
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sus_scheduling_database
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - TZ=America/Sao_Paulo
    ports:
      - "5434:5432"
    networks:
      - sus-scheduling-network

  sus-scheduling-app:
    container_name: java-sus-scheduling
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "mvn clean install && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar target/sus_scheduling.jar"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8082:8080"
      - "5007:5005"
    networks:
      - sus-scheduling-network
    #      - rabbitmq_go_net
    depends_on:
      - sus-scheduling-db

networks:
  #  rabbitmq_go_net:
  #    external: true
  sus-scheduling-network:
    name: sus-scheduling-network